# Project: TreinamentoED
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o funcrecursivas.o
LINKOBJ  = main.o funcrecursivas.o
LIBS     = -L"C:/Arquivos de programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/include" -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/include" -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Arquivos de programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TreinamentoED.exe
CXXFLAGS = $(CXXINCS) -ansi -m32
CFLAGS   = $(INCS) -ansi -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

funcrecursivas.o: funcrecursivas.c
	$(CC) -c funcrecursivas.c -o funcrecursivas.o $(CFLAGS)
